# Generated by Django 5.0.7 on 2024-07-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
